
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - manager.keikoproj.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - manager.keikoproj.io
  resources:
  - clusters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - manager.keikoproj.io
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - manager.keikoproj.io
  resources:
  - namespaces/status
  verbs:
  - get
  - update
  - patch
