apiVersion: manager.keikoproj.io/v1alpha1
kind: NamespaceTemplate
metadata:
  name: namespacetemplate-sample
spec:
  exportedParamName:
    - registry
    - env
    - name
  nsResources:
    namespace:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          imageregistry.com: ${registry}
          something.com/permitted: some-role
        labels:
          environment: ${env}
        name: ${name}
    resources:
      - name: local_service_account1
        type: ServiceAccount
        serviceAccount:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: dev-sa
            namespace: ${name}
      - name: local_service_account2
        type: ServiceAccount
        serviceAccount:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: dev-sa2
            namespace: ${name}
      - name: local_role
        type: Role
        role:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: dev-role
          rules:
            - apiGroups:
                - ""
              resources:
                - pods/attach
                - pods/exec
                - pods/portforward
                - pods/proxy
                - secrets
                - services/proxy
              verbs:
                - get
                - list
                - watch
                - create
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - impersonate
            - apiGroups:
                - ""
              resources:
                - pods
                - pods/attach
                - pods/exec
                - pods/portforward
                - pods/proxy
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - watch
                - update
            - apiGroups:
                - ""
              resources:
                - configmaps
                - endpoints
                - persistentvolumeclaims
                - replicationcontrollers
                - replicationcontrollers/scale
                - secrets
                - serviceaccounts
                - services
                - services/proxy
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - daemonsets
                - deployments
                - deployments/rollback
                - deployments/scale
                - replicasets
                - replicasets/scale
                - statefulsets
                - statefulsets/scale
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
                - watch
            - apiGroups:
                - autoscaling
              resources:
                - horizontalpodautoscalers
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
            - apiGroups:
                - batch
              resources:
                - cronjobs
                - jobs
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
            - apiGroups:
                - extensions
              resources:
                - daemonsets
                - deployments
                - deployments/rollback
                - deployments/scale
                - replicasets
                - replicasets/scale
                - networkpolicies
                - replicationcontrollers/scale
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - get
                - list
                - create
                - delete
                - deletecollection
                - patch
                - update
      - name: local_role_binding
        type: RoleBinding
        roleBinding:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: dev-rolebinding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: dev-role
          subjects:
            - kind: ServiceAccount
              name: dev-sa
              namespace: ${name}