apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: system
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - command:
        - /app
        image: server:latest
        name: server
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
